# Autogenerated by fastlane
#
# Ensure this file is checked in to source control!

ruby '2.4.2'

source "https://rubygems.org"

gem 'fastlane'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
